name: medsam2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py312h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.4=h5148396_1
  - pyzmq=25.1.2=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py312h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - acvl-utils==0.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - asyncio-atexit==1.0.1
      - attrs==23.2.0
      - babel==2.15.0
      - backoff==2.2.1
      - batchgenerators==0.25
      - batchgeneratorsv2==0.2
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - connected-components-3d==3.18.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dicom2nifti==2.4.11
      - dynamic-network-architectures==0.3.1
      - einops==0.8.0
      - fastjsonschema==2.20.0
      - fft-conv-pytorch==1.2.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - future==1.0.0
      - googleapis-common-protos==1.63.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - hydra-core==1.3.2
      - idna==3.7
      - imagecodecs==2024.6.1
      - imageio==2.34.2
      - importlib-metadata==6.11.0
      - iopath==0.1.10
      - ipympl==0.9.4
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mistune==3.0.2
      - monai==1.3.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.3
      - nibabel==5.2.1
      - nnunetv2==2.5.1
      - notebook-shim==0.2.4
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - pillow==10.4.0
      - portalocker==2.10.1
      - prometheus-client==0.20.0
      - protobuf==4.25.4
      - psutil==5.9.8
      - pycparser==2.22
      - pydicom==2.4.4
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - graphviz==0.20.3
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.19.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - simpleitk==2.3.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sympy==1.13.1
      - synapseclient==4.4.0
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tinycss2==1.3.0
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchsummary==1.5.1
      - torchvision==0.19.0
      - tqdm==4.66.4
      - traceback2==1.4.0
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - unittest2==1.1.0
      - uri-template==1.3.0
      - urllib3==1.26.19
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - yacs==0.1.8
